sudo: required

git:
  submodules: true

services:
  - docker

before_install:
  - docker build -t andreabettelli/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run andreabettelli/client-test npm test -- --coverage

after_success:
  - docker build -t andreabettelli/multi-client ./client
  - docker build -t andreabettelli/multi-nginx ./nginx
  - docker build -t andreabettelli/multi-server ./server
  - docker build -t andreabettelli/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub.
  - docker push andreabettelli/multi-client
  - docker push andreabettelli/multi-nginx
  - docker push andreabettelli/multi-server
  - docker push andreabettelli/multi-worker
